Upgrade Rails version to 6.1.6
cartona/activeadmin_addons pull request #1
Opened 2022-06-12 17:22 UTC by Hossam-Hawary

Fix: undefined method parent error

2022-06-15 14:19 UTC, ma7dy requested changes
Why the invoice , department, cities models are in active admin ?

2022-06-15 14:38 UTC, Hossam-Hawary commented on .rubocop.yml
> +<<<<<<< HEAD
Resolved

2022-06-15 14:38 UTC, Hossam-Hawary commented on .rubocop.yml
> +<<<<<<< HEAD
Resolved

2022-06-19 09:07 UTC, ma7dy commented
👍

2022-06-21 13:10 UTC, ma7dy approved these changes

2022-06-21 13:11 UTC, merged